"""
phase4/emailer.py
------------------
Phase 4 – Email Delivery.

Builds a multipart MIME email (plain text + HTML) from a pulse Markdown note
and either:
  - Dry-run (default): writes the raw message bytes to data/reports/pulse-YYYY-MM-DD.eml
  - Live send (--send): connects via SMTP (TLS) and sends the message.

SMTP credentials come from environment variables:
  SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD,
  EMAIL_FROM, EMAIL_TO (comma-separated)
"""

from __future__ import annotations

import logging
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Markdown → plain text / HTML converters
# ---------------------------------------------------------------------------

def _md_to_plain(markdown: str) -> str:
    """Very lightweight Markdown → plain text (strip # and * markers)."""
    import re
    text = re.sub(r"^#{1,6}\s+", "", markdown, flags=re.MULTILINE)  # headings
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)                    # bold
    text = re.sub(r"\*(.+?)\*", r"\1", text)                        # italic
    text = re.sub(r"^>\s*", "  ", text, flags=re.MULTILINE)         # blockquotes
    return text.strip()


def _md_to_html(markdown: str, subject: str) -> str:
    """Convert Markdown pulse note to a simple, readable HTML email body."""
    import re

    html_lines: list[str] = []
    for line in markdown.splitlines():
        if line.startswith("# "):
            html_lines.append(f"<h1>{line[2:].strip()}</h1>")
        elif line.startswith("## "):
            html_lines.append(f"<h2>{line[3:].strip()}</h2>")
        elif line.startswith("### "):
            html_lines.append(f"<h3>{line[4:].strip()}</h3>")
        elif line.startswith("> "):
            content = line[2:].strip()
            html_lines.append(f'<blockquote style="border-left:4px solid #4CAF50;margin:8px 0;padding:4px 12px;color:#333;">{content}</blockquote>')
        elif re.match(r"^\d+\.\s", line):
            # numbered list item — wrap individually (simple approach)
            content = re.sub(r"^\d+\.\s+", "", line)
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
            html_lines.append(f"<li>{content}</li>")
        elif line.strip() == "":
            html_lines.append("<br>")
        else:
            line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            html_lines.append(f"<p>{line}</p>")

    body = "\n".join(html_lines)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{subject}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           max-width: 680px; margin: 0 auto; padding: 24px; color: #1a1a1a; }}
    h1   {{ color: #1a73e8; border-bottom: 2px solid #e8f0fe; padding-bottom: 8px; }}
    h2   {{ color: #174ea6; margin-top: 24px; }}
    li   {{ margin: 6px 0; }}
    blockquote {{ background: #f8f9fa; border-radius: 4px; }}
    footer {{ margin-top: 32px; font-size: 12px; color: #888; }}
  </style>
</head>
<body>
{body}
<footer>Generated by App Review Insights Analyser &mdash; do not reply.</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# MIME message builder
# ---------------------------------------------------------------------------

def build_message(
    markdown: str,
    subject: str,
    from_addr: str,
    to_addrs: list[str],
) -> MIMEMultipart:
    """
    Build a multipart/alternative MIME message from the pulse Markdown.

    Returns a :class:`MIMEMultipart` object ready to be either saved or sent.
    """
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = ", ".join(to_addrs)

    plain = _md_to_plain(markdown)
    html = _md_to_html(markdown, subject)

    # RFC 2046: last part is preferred — attach HTML last
    msg.attach(MIMEText(plain, "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))

    logger.debug("Built MIME message: subject=%r  to=%r", subject, to_addrs)
    return msg


# ---------------------------------------------------------------------------
# Dry-run writer
# ---------------------------------------------------------------------------

def write_eml(msg: MIMEMultipart, output_path: Path) -> Path:
    """
    Serialise *msg* to an RFC-822 .eml file without sending it.

    Returns the path of the created file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(msg.as_bytes())
    logger.info("Dry-run: email written to %s", output_path)
    return output_path


# ---------------------------------------------------------------------------
# Live SMTP sender
# ---------------------------------------------------------------------------

def send_email(
    msg: MIMEMultipart,
    host: str,
    port: int,
    username: str,
    password: str,
) -> None:
    """
    Send *msg* via SMTP with STARTTLS.

    Parameters
    ----------
    msg:      The MIME message to send.
    host:     SMTP server hostname (e.g. 'smtp.gmail.com').
    port:     SMTP port (587 for STARTTLS, 465 for SSL).
    username: SMTP login username.
    password: SMTP login password / app-password.
    """
    from_addr = msg["From"]
    to_addrs = [addr.strip() for addr in msg["To"].split(",")]

    context = ssl.create_default_context()

    if port == 465:
        # SMTP_SSL (implicit TLS)
        logger.info("Connecting to %s:%d (SSL)…", host, port)
        with smtplib.SMTP_SSL(host, port, context=context) as server:
            server.login(username, password)
            server.sendmail(from_addr, to_addrs, msg.as_bytes())
    else:
        # STARTTLS (port 587 typical)
        logger.info("Connecting to %s:%d (STARTTLS)…", host, port)
        with smtplib.SMTP(host, port) as server:
            server.ehlo()
            server.starttls(context=context)
            server.ehlo()
            server.login(username, password)
            server.sendmail(from_addr, to_addrs, msg.as_bytes())

    logger.info("Email sent to: %s", to_addrs)
